### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by guhyeon** [lifeomic/axios-fetch#120]
TypeError: Cannot read properties of undefined (reading 'name')

Its caused by isHeaders at typeUtils.js line 12.

I think it should be using optional chain operator.

const isHeaders = (headers) => headers.constructor.name === 'Headers';
=>const isHeaders = (headers) => headers.constructor?.name === 'Headers';

**Comment by mdlavin** [comment]
This was fixed in #119 and will be released in a new version when #122 is merged
