### ISSUE TITLE
Problem creating production build: Failed to minify the code from this file...

### ISSUE THREAD

**Issue by baleeds** [lifeomic/axios-fetch#14]
I'm getting an error when I try to create a production build with create-react-app.  My package.json currently is using
```
"@lifeomic/axios-fetch": "bouldercare/axios-fetch"
```

The build (npm run build) fails with the following error.
```
Creating an optimized production build...

Failed to compile.



Failed to minify the code from this file: 



 	./node_modules/@lifeomic/axios-fetch/src/index.js:6 



Read more here: http://bit.ly/2tRViJ9
```

Any ideas why the code would fail to minify?

**Comment by mdlavin** [comment]
I notice that you are pointing at a fork of this project. Do you see the same problem when using the publish version of the project?

**Comment by baleeds** [comment]
Yes it does, although it's pointing to `index.js:1` as the problem now.  I have temporarily changed my package to `"@lifeomic/axios-fetch": "^1.4.0",`.

**Comment by mdlavin** [comment]
We minify projects that use axios-fetch often at LifeOmic without trouble so I'm guessing that some unique config is causing trouble for you. One gotcha I've seen is that not all minifiers support the latest Javascript syntax. Can you share some details about your minification process and configuration?

**Comment by baleeds** [comment]
Well, we are using create-react-app, so most of that is abstracted away.  It uses babel to transpile es6 and then webpack to create the minified bundle.
Our babelrc is:
```
{
  "presets": [
    "react-app"
  ]
}
```
But it does seem like it's a configuration issue, especially a babel issue, since it probably shouldn't be trying to minify any es6 code to begin with.

**Comment by baleeds** [comment]
Hmm, I think I may have fixed it.  I did two things.

1. Updated my react dependencies to the latest versions.
2. Deleted my yarn.lock, package.lock, and node_modules.  Then ran yarn from scratch.

**Comment by mdlavin** [comment]
That's great news! Do you mind if I close this issue?

**Comment by baleeds** [comment]
Go for it!
