### ISSUE TITLE
npmjs is missing versions

### ISSUE THREAD

**Issue by tm1000** [lifeomic/axios-fetch#26]
npmjs is missing

- 1.4.0
- 1.3.1
- 1.3.0
- 1.2.0

Can you publish those?

**Comment by mdlavin** [comment]
Sorry I missed this. It's possible to publish them, but I'm curious why you were interested in them. Can you share?

**Comment by tm1000** [comment]
@mdlavin I'm using your library (this library) to be able to use axios as 'fetch' in Apollo Client. It works very well. Would just be nice to have the new stuff you've done in NPM.

**Comment by mdlavin** [comment]
it looks to me like the latest version 1.4.1 is published to npm: https://www.npmjs.com/package/@lifeomic/axios-fetch/v/1.4.1

**Comment by tm1000** [comment]
@mdlavin 

Thank you Matt. I was looking at https://www.npmjs.com/package/axios-fetch which is obviously old! ugh! anyways thank you for posting the new link :-D
