### ISSUE TITLE
1.5.0 Release breaks Apollo

### ISSUE THREAD

**Issue by tm1000** [lifeomic/axios-fetch#58]
With this release no JSON can be parsed. The error in the browser is `The provided value 'stream' is not a valid enum value of type XMLHttpRequestResponseType` along with being unable to parse JSON

**Comment by tm1000** [comment]
Seems to be related to this change:

https://github.com/lifeomic/axios-fetch/commit/b5b933ee4478183045c5827dc6ea90b5045d00b7

**Comment by mdlavin** [comment]
Sorry about the breaking change. The intention was not to introduce a breaking change. I'll try to find a non-breaking version of the fix for new versions of Axios.

**Comment by mdlavin** [comment]
@tm1000 Can you retest with 1.5.1?

**Comment by tm1000** [comment]
@mdlavin Thanks for the quick work! It looks to be working great! Appreciate your contributions to open source!
