### ISSUE TITLE
`.finally()` is not a function

### ISSUE THREAD

**Issue by wSedlacek** [lifeomic/axios-fetch#61]
This issue appears to be an upstream issue with `node-fetch` with it's home grown promises, but this does cause errors with when attempting to use this library with others that do expect `.finally()` to exist.

It seems that the next version of `node-fetch` will support promises, so that is worth keeping an eye on.

**Comment by mdlavin** [comment]
Thanks for the heads up. When the new version of `node-fetch` is released, would you be up for creating a PR to upgrade?

**Comment by wSedlacek** [comment]
Sure! Do you want a PR for the beta we have right now or to wait for the full release of `node-fetch` 3

**Comment by mdlavin** [comment]
Let's wait for the full release. It seems like they've been in pre-release mode for a long time. I'd feel safer waiting for the final one

**Comment by wSedlacek** [comment]
Until this is fixed, would you like a PR for the README.md to document this?

**Comment by mdlavin** [comment]
A PR to update the README sounds good for now. Thanks for the offer
