### ISSUE TITLE
Update package.json types to reference index.d.ts

### ISSUE THREAD

**Issue by catc** [lifeomic/axios-fetch#96]
Currently `index.ts` is being used as [`types` in package.json](https://github.com/lifeomic/axios-fetch/blob/master/package.json#L6) which is causing compiler errors when upgrading to newer versions of typescript (since it tries to compile the entire package instead of just referencing the types). I think this could be resolved by generating an [`index.d.ts`](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html) and referencing that instead.

**Comment by DavidTanner** [comment]
Would it solve both our issues if we were to publish both, and point the types to the `.d.ts` file?
